#!/bin/bash
clear

working_directory=`pwd`

function exec_windows {
    echo $* | cmd.exe>/dev/null
}

pathw=`wslpath -m "$*" | sed 's/\\//\\\\/g'`

echo -e "\033[42m\033[30m >>> \033[0m Target directory is \033[32m$pathw\033[0m."
echo

for files_to_link in `find ./src -mindepth 2 -maxdepth 2`; do
    cd $working_directory
    echo -e "\033[43m\033[30m </> \033[0m Symlinking \033[32m$files_to_link\033[0m..."
    target=$pathw\\`echo $files_to_link | cut -b 7- | sed 's/\\//\\\\/g'`
    source=`wslpath -m $files_to_link | sed 's/\\//\\\\/g'`
    cd /mnt/c/
    exec_windows rmdir /S /Q \"$target\"
    exec_windows mklink /D \"$target\" \"$source\"
done

cd $working_directory

echo

echo -e "\033[42m\033[30m ^O^ \033[0m Done!"

#exec_windows "mklink /D \"`wslpath -m \"$pathw\\config\\defaultoptions\" | sed 's/\\//\\\\/g'`\" `wslpath -m ./src/config/defaultoptions | sed 's/\\//\\\\/g'`"