[general.general]
dropAbilitiesOnPlayerDeath = 0
totemMaximumSpawnRarity = -1

[core.general]
analytics = false

[core.ability_totem]
lootChests = false
totemCraftingCount = 0

[ability.flight]
obtainableOnMobSpawn = false

[ability.luck]
obtainableOnMobSpawn = false

[ability.strength]
obtainableOnMobSpawn = false

[ability.regeneration]
obtainableOnMobSpawn = false

[ability.fertility]
obtainableOnMobSpawn = false

[ability.speed]
obtainableOnMobSpawn = false

[ability.saturation]
obtainableOnMobSpawn = false

[ability.weakness]
obtainableOnMobSpawn = false

[ability.mining_fatigue]
obtainableOnMobSpawn = false

[ability.levitation]
obtainableOnMobSpawn = false

[ability.night_vision]
obtainableOnMobSpawn = false

[ability.power_stare]
obtainableOnMobSpawn = false

[ability.poison]
obtainableOnMobSpawn = false

[ability.absorbtion]
obtainableOnMobSpawn = false

[ability.blindness]
obtainableOnMobSpawn = false

[ability.water_breathing]
obtainableOnMobSpawn = false

[ability.bonemealer]
obtainableOnMobSpawn = false

[ability.fire_resistance]
obtainableOnMobSpawn = false

[ability.slowness]
obtainableOnMobSpawn = false

[ability.haste]
obtainableOnMobSpawn = false

[ability.jump_boost]
obtainableOnMobSpawn = false

[ability.unluck]
obtainableOnMobSpawn = false

[ability.resistance]
obtainableOnMobSpawn = false

[ability.invisibility]
obtainableOnMobSpawn = false

[ability.nausea]
obtainableOnMobSpawn = false

[ability.hunger]
obtainableOnMobSpawn = false

[ability.glowing]
obtainableOnMobSpawn = false

[ability.step_assist]
obtainableOnMobSpawn = false

[ability.magnetize]
obtainableOnMobSpawn = false

[ability.wither]
obtainableOnMobSpawn = false
