[Singularities]
defaultRecipes = false

["Combination Crafting"]
enabled = false

["Table Crafting"]
autoTablesEnabled = false

["Quantum Compression"]
enabled = false

["Recipe Maker"]
enabled = false
